apiVersion: v1
kind: ReplicationController
metadata:
  name: registry-rc
  namespace: harbor
  labels:
    name: registry-rc
spec:
  replicas: 1
  selector:
    name: registry-apps
  template:
    metadata:
      namespace: harbor
      labels:
        name: registry-apps
    spec:
      containers:
      - name: registry-app
        image: test.caicloud.io/harbor/registry:0.4.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        - containerPort: 5001
        volumeMounts:
        - name: config
          mountPath: /etc/docker/registry
        - name: storage
          mountPath: /storage
      volumes:
      - name: config
        configMap:
          name: harbor-registry-config
          items:
          - key: config
            path: config.yml
          - key: cert
            path: root.crt
      - name: storage
        hostPath:
          path: /data/registry 
